name: Create PR from Template Changes
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Hub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y hub

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch Changes from Template Repo
        run: |
          git remote add template https://github.com/rh-hideout/pokeemerald-expansion.git
          git fetch template
          git checkout -b template-branch template/master

      - name: Create PR
        run: |
          git push origin template-branch:template-branch
          hub pull-request -m "Merge changes from the template repo" -b master -h template-branch -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
