name: CI

on:
  push:
    branches:
      - master
      - upcoming
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout agbcc
        uses: actions/checkout@v2
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install agbcc
        run: |
          ./install.sh /home/zac/rhh_actions-runner/_work/pokeemerald-expansion/pokeemerald-expansion
        working-directory: /home/zac/agbcc

      - name: Agbcc
        run: make -j${nproc} -O all

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O all

      - name: Test
        env:
          TEST: 1
        run: |
          make -j${nproc} -O pokeemerald-test.elf
          make -j${nproc} check
